services:
  rag-api:
    build: .
    restart: unless-stopped
    env_file: .env
    depends_on:
      - ollama
    network_mode: "host"  # Gives direct access to local network

  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
        - ./ollama/ollama:/root/.ollama
        - ./ollama_entrypoint.sh:/entrypoint.sh
    entrypoint: [ "/usr/bin/bash", "/entrypoint.sh" ]


networks:
  rag-network:
    driver: bridge

volumes:
  ollama-data: